"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Bell, Check, Copy, Gift, Loader2, Medal, Search, Share2, Sparkles, Trophy, UserRound, WalletCards } from "lucide-react";

type Section = "dashboard"|"referral"|"points"|"rewards"|"redemptions"|"withdrawals"|"leaderboard"|"notifications"|"activity"|"profile"|"help";
const card="rounded-2xl border border-white/8 bg-[#111a2a]";
const input="w-full rounded-xl border border-white/10 bg-[#0b1321] px-3.5 py-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-[#ff6b35]";
const primary="inline-flex items-center justify-center gap-2 rounded-xl bg-[#ff6b35] px-4 py-2.5 text-sm font-black text-white hover:bg-[#ff7d4d] disabled:opacity-40";
const secondary="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-4 py-2.5 text-sm font-semibold text-slate-200 hover:bg-white/[.07]";

export default function PortalPageClient({section}:{section:Section}){
  const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
  async function load(){setLoading(true);setError("");try{const r=await fetch(`/api/member/portal/${section}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memuat data");setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[section]);
  if(loading)return <Loading/>;
  if(error)return <Empty title="Data belum bisa dimuat" text={error} action={<button className={secondary} onClick={()=>void load()}>Coba lagi</button>}/>;
  const p={data,load,setNotice};
  return <div className="space-y-5">{notice&&<div role="status" className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-200">{notice}</div>}{section==="dashboard"&&<Dashboard {...p}/>} {section==="referral"&&<Referral {...p}/>} {section==="points"&&<Points {...p}/>} {section==="rewards"&&<Rewards {...p}/>} {section==="redemptions"&&<Redemptions {...p}/>} {section==="withdrawals"&&<Withdrawals {...p}/>} {section==="leaderboard"&&<Leaderboard {...p}/>} {section==="notifications"&&<Notifications {...p}/>} {section==="activity"&&<Activity {...p}/>} {section==="profile"&&<Profile {...p}/>} {section==="help"&&<Help {...p}/>}</div>;
}

function Head({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#ff8b63]">{eyebrow}</p><h1 className="mt-1 text-2xl font-black tracking-tight md:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">{text}</p></div>{action}</div>}
function Metric({label,value}:{label:string;value:any}){return <div className={`${card} p-4`}><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>}
function Status({value}:{value:string}){const v=String(value||"").toLowerCase();const c=v==="success"||v==="approved"||v==="completed"||v==="active"?"text-emerald-300 bg-emerald-400/10":v==="pending"||v==="held"?"text-amber-300 bg-amber-400/10":v==="rejected"?"text-rose-300 bg-rose-400/10":"text-slate-300 bg-white/5";return <span className={`rounded-full px-2.5 py-1 text-[11px] font-bold capitalize ${c}`}>{v.replaceAll("_"," ")}</span>}
const fmt=(v:any)=>new Intl.NumberFormat("id-ID").format(Number(v||0));
const date=(v:any)=>new Date(v).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"});

function Dashboard({data}:{data:any}){const r=data.nextReward;const remain=r?Math.max(0,Number(r.points_required)-data.points.available):0;const pct=r?Math.min(100,Math.round(data.points.available/Math.max(1,Number(r.points_required))*100)):100;return <><Head eyebrow="Dashboard" title={`Halo, ${data.member.name.split(" ")[0]} 👋`} text="Ringkasan Member yang fokus pada progres, hasil referral, dan request yang perlu kamu perhatikan." action={<Link className={primary} href="/member/referral"><Share2 size={16}/>Bagikan Link Referral</Link>}/><section className={`${card} p-5 md:p-6`}><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div><p className="text-sm font-bold text-[#ff8b63]">Reward terdekat</p><h2 className="mt-2 text-2xl font-black">{r?`${remain} poin lagi menuju ${r.name}`:"Semua reward aktif sudah terjangkau"}</h2><p className="mt-2 text-sm text-slate-400">Kamu sudah memiliki {data.points.available} poin tersedia.</p><div className="mt-5 h-2.5 rounded-full bg-white/6"><div className="h-full rounded-full bg-[#ff6b35]" style={{width:`${pct}%`}}/></div></div><div className="grid grid-cols-2 gap-3"><Metric label="Poin tersedia" value={data.points.available}/><Metric label="Poin di-hold" value={data.points.held}/><Metric label="Referral bulan ini" value={data.monthly?.referrals||0}/><Metric label="Request pending" value={(data.pending?.pending_redemptions||0)+(data.pending?.pending_withdrawals||0)}/></div></div></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["/member/referral","Copy Referral"],["/member/rewards","Lihat Reward"],["/member/withdrawals","Ajukan Withdrawal"],["/member/leaderboard","Cek Peringkat"]].map(([href,label])=><Link key={href} href={href} className={`${card} p-4 font-bold hover:border-[#ff6b35]/35`}>{label}</Link>)}</div><List title="Aktivitas terbaru" rows={data.recentActivity?.map((x:any)=>({id:x.created_at,title:x.label,sub:x.note||date(x.created_at),right:`${x.points>0?"+":""}${x.points} poin`}))||[]} empty="Belum ada aktivitas."/></>}

function Referral({data,setNotice}:{data:any;setNotice:(v:string)=>void}){const [origin,setOrigin]=useState("");useEffect(()=>setOrigin(window.location.origin),[]);const url=`${origin}${data.referralUrl}`;const msg=`Aku pakai DorizzStore. Checkout lewat link referral ini: ${url}`;async function copy(){await navigator.clipboard.writeText(url);setNotice("Link referral berhasil disalin.")}async function share(){if(navigator.share)await navigator.share({title:"DorizzStore",text:msg,url});else await copy()}return <><Head eyebrow="Referral" title="Ajak teman dari satu link" text={`Attribution ${data.referralWindowDays} hari, last-click, hanya customer baru dengan transaksi pertama sukses yang eligible.`} action={<button className={primary} onClick={share}><Share2 size={16}/>Bagikan Link</button>}/><section className={`${card} p-5`}><div className="flex flex-col gap-2 md:flex-row"><input readOnly value={url} className={`${input} font-mono text-xs`}/><button className={secondary} onClick={copy}><Copy size={15}/>Copy</button><a className={secondary} target="_blank" rel="noreferrer" href={`https://wa.me/?text=${encodeURIComponent(msg)}`}>WhatsApp</a></div><p className="mt-4 rounded-xl bg-white/[.025] p-4 text-sm text-slate-400">Preview: “{msg}”</p></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total referral" value={data.summary.total}/><Metric label="Sukses bulan ini" value={data.monthly.successful}/><Metric label="Poin referral" value={data.summary.points}/><Metric label="Poin / referral" value={data.referralPoints}/></div><List title="Riwayat referral" rows={data.history.map((x:any)=>({id:x.id,title:x.customer_name,sub:`${date(x.created_at)} • ${x.is_self_referral?"Self referral":x.points_awarded>0?"Eligible":"Tidak eligible"}`,right:`${x.points_awarded} poin`}))} empty="Belum ada referral. Bagikan link kamu untuk mulai mengumpulkan poin."/></>}

function Points({data}:{data:any}){const [q,setQ]=useState("");const [status,setStatus]=useState("all");const rows=useMemo(()=>data.ledger.filter((x:any)=>(status==="all"||x.status===status)&&`${x.label} ${x.note||""}`.toLowerCase().includes(q.toLowerCase())),[data,q,status]);return <><Head eyebrow="Member Wallet" title="Poin" text="Lihat poin tersedia, di-hold, lifetime earned, dan histori ledger dalam bahasa manusia."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Available" value={data.points.available}/><Metric label="Held" value={data.points.held}/><Metric label="Lifetime earned" value={data.points.lifetimeEarned}/><Metric label="Nilai available" value={`Rp ${fmt(data.points.available*data.points.pointValue)}`}/></div><div className={`${card} flex flex-col gap-2 p-3 sm:flex-row`}><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input className={`${input} pl-10`} value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari aktivitas poin..."/></div><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option><option value="available">Available</option><option value="held">Held</option><option value="spent">Spent</option><option value="returned">Returned</option></select></div><List title="Point ledger" rows={rows.map((x:any)=>({id:x.id,title:x.label,sub:`${x.note||""} • ${date(x.created_at)} • ${x.status}`,right:`${x.points>0?"+":""}${x.points} poin`}))} empty="Belum ada aktivitas poin."/></>}

function Rewards({data,load,setNotice}:{data:any;load:()=>Promise<void>;setNotice:(v:string)=>void}){async function redeem(id:string){const r=await fetch("/api/member/redemptions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rewardId:id})});const j=await r.json();setNotice(r.ok?"Reward diajukan. Poin sekarang di-hold sampai request diproses.":j.error||"Gagal menukar reward");if(r.ok)await load()}return <><Head eyebrow="Reward" title="Katalog benefit Member" text="Reward yang dekat dengan saldo kamu menampilkan progres nyata tanpa scarcity atau countdown palsu."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.rewards.map((r:any)=>{const lack=Math.max(0,r.points_required-data.points.available);const pct=Math.min(100,Math.round(data.points.available/Math.max(1,r.points_required)*100));return <article key={r.id} className={`${card} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-violet-300">{r.fulfillment_type==="dorizz_voucher"?"Voucher Dorizz":"Member Benefit"}</p><h2 className="mt-1 text-lg font-black">{r.name}</h2></div><Gift className="text-violet-300" size={20}/></div><p className="mt-3 text-sm leading-6 text-slate-400">{r.description||"Reward Member DorizzStore"}</p><div className="mt-4 h-2 rounded-full bg-white/6"><div className="h-full rounded-full bg-violet-400" style={{width:`${pct}%`}}/></div><p className={`mt-2 text-xs ${lack?"text-amber-300":"text-emerald-300"}`}>{lack?`Kurang ${lack} poin`:"Siap ditukar"}</p><button className={`${primary} mt-4 w-full`} disabled={lack>0} onClick={()=>void redeem(r.id)}>{lack?`Kurang ${lack} poin`:"Tukar reward"}</button></article>})}</div></>}

function Redemptions({data,setNotice}:{data:any[];setNotice:(v:string)=>void}){async function copy(v:string){await navigator.clipboard.writeText(v);setNotice("Kode voucher disalin.")}return <><Head eyebrow="Penukaran Saya" title="Status reward kamu" text="Voucher hanya tampil setelah approval. Jika ditolak, alasan ditampilkan dengan jelas."/><div className="grid gap-4 lg:grid-cols-2">{data.length?data.map(x=><article key={x.id} className={`${card} p-5`}><div className="flex justify-between gap-3"><div><p className="text-xs text-slate-500">{date(x.created_at)}</p><h2 className="mt-1 font-black">{x.reward_name}</h2><p className="mt-1 text-sm text-slate-400">{x.points} poin</p></div><Status value={x.status}/></div>{x.voucher_code&&x.status==="approved"&&<div className="mt-4 flex items-center justify-between gap-3 rounded-xl bg-emerald-400/8 p-3"><code className="font-black">{x.voucher_code}</code><button className={secondary} onClick={()=>void copy(x.voucher_code)}><Copy size={14}/>Copy</button></div>}{x.rejection_reason&&<p className="mt-4 text-sm text-rose-300">Alasan: {x.rejection_reason}</p>}</article>):<Empty title="Belum ada penukaran" text="Pilih reward dari katalog Member." action={<Link className={primary} href="/member/rewards">Lihat Reward</Link>}/>}</div></>}

function Withdrawals({data,load,setNotice}:{data:any;load:()=>Promise<void>;setNotice:(v:string)=>void}){const [points,setPoints]=useState(data.minimum);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.points=Number(body.points);const r=await fetch("/api/member/withdrawals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();setNotice(r.ok?`Withdrawal diajukan senilai Rp ${fmt(j.amountRupiah)}.`:j.error||"Gagal mengajukan withdrawal");if(r.ok)await load()}return <><Head eyebrow="Withdrawal" title="Cairkan poin dengan transparan" text="Poin menjadi hold saat request dibuat dan akan kembali jika request ditolak."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Poin tersedia" value={data.points.available}/><Metric label="Nilai 1 poin" value={`Rp ${fmt(data.points.pointValue)}`}/><Metric label="Minimum" value={`${data.minimum} poin`}/><Metric label="Maksimum" value={`Rp ${fmt(data.points.available*data.points.pointValue)}`}/></div><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><form className={`${card} space-y-3 p-5`} onSubmit={submit}><h2 className="font-black">Ajukan withdrawal</h2><input name="points" type="number" min={data.minimum} max={data.points.available} value={points} onChange={e=>setPoints(Number(e.target.value))} className={input} required/><div className="rounded-xl bg-amber-400/8 p-3 text-sm text-amber-200">Estimasi: <b>Rp {fmt(points*data.points.pointValue)}</b></div><input name="method" className={input} placeholder="Bank / e-wallet" required/><input name="accountNumber" className={input} placeholder="Nomor rekening / akun" required/><input name="accountName" className={input} placeholder="Nama pemilik" required/><button className={`${primary} w-full`} disabled={points<data.minimum||points>data.points.available}>Ajukan Withdrawal</button></form><List title="Riwayat withdrawal" rows={data.history.map((x:any)=>({id:x.id,title:`Rp ${fmt(x.amount_rupiah)} • ${x.status}`,sub:`${x.points} poin • ${x.method} • ${date(x.created_at)}${x.rejection_reason?` • ${x.rejection_reason}`:""}`,right:null}))} empty="Belum ada withdrawal."/></div></>}

function Leaderboard({data}:{data:any}){return <><Head eyebrow="Leaderboard" title="Kompetisi yang sehat" text={data.self?`Posisi kamu #${data.self.rank} dengan ${data.self.points} poin bulan ini.`:"Mulai referral untuk masuk leaderboard."}/>{data.pointsToTop10>0&&<div className="rounded-xl border border-cyan-400/15 bg-cyan-400/8 p-4 text-sm text-cyan-200">Kamu hanya <b>{data.pointsToTop10} poin</b> dari Top 10.</div>}<div className="grid gap-3 md:grid-cols-3">{data.top10.slice(0,3).map((x:any)=><div key={x.rank} className={`${card} p-5`}><Trophy size={20} className={x.rank===1?"text-amber-300":"text-slate-500"}/><p className="mt-4 text-xs text-slate-500">Peringkat #{x.rank}</p><h2 className="font-black">{x.name}</h2><p className="mt-1 text-emerald-300">{x.points} poin</p></div>)}</div><List title="Peringkat 4–10" rows={data.top10.slice(3).map((x:any)=>({id:x.rank,title:`#${x.rank} ${x.name}`,sub:"Poin referral bulan ini",right:`${x.points} poin`}))} empty="Belum ada peringkat tambahan."/></>}

function Notifications({data,load,setNotice}:{data:any[];load:()=>Promise<void>;setNotice:(v:string)=>void}){async function mark(body:any){const r=await fetch("/api/member/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(r.ok){setNotice("Notifikasi diperbarui.");await load()}}return <><Head eyebrow="Notifikasi" title="Notification Center" text="Approval, penolakan, poin masuk, campaign, dan sistem Member." action={<button className={secondary} onClick={()=>void mark({all:true})}><Check size={15}/>Tandai semua dibaca</button>}/>{data.length?<div className={`${card} divide-y divide-white/6`}>{data.map(x=><button key={x.id} className={`flex w-full gap-3 p-4 text-left ${x.is_read?"opacity-60":""}`} onClick={()=>!x.is_read&&void mark({id:x.id})}><Bell size={17} className="mt-1 text-[#ff8b63]"/><div><p className="font-bold">{x.title}</p><p className="mt-1 text-sm text-slate-400">{x.message}</p><p className="mt-2 text-xs text-slate-600">{date(x.created_at)}</p></div></button>)}</div>:<Empty title="Belum ada notifikasi" text="Update penting akan muncul di sini."/>}</>}

function Activity({data}:{data:any[]}){return <><Head eyebrow="Riwayat Aktivitas" title="Timeline Member" text="Referral, poin, reward, withdrawal, dan adjustment penting dalam satu timeline."/><List title="Semua aktivitas" rows={data.map((x:any)=>({id:`${x.kind}-${x.id}`,title:x.label||x.message,sub:`${date(x.created_at)} • ${x.status}`,right:x.points!==null&&x.points!==undefined?`${x.points>0?"+":""}${x.points} poin`:null}))} empty="Belum ada aktivitas."/></>}

function Profile({data,load,setNotice}:{data:any;load:()=>Promise<void>;setNotice:(v:string)=>void}){async function save(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.action=action;const r=await fetch("/api/member/profile",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();setNotice(r.ok?j.message:j.error||"Gagal menyimpan");if(r.ok)await load()}return <><Head eyebrow="Profil & Keamanan" title="Akun Member" text="Referral code tidak dapat diubah agar attribution tetap konsisten."/><div className="grid gap-5 xl:grid-cols-2"><form onSubmit={e=>void save(e,"profile")} className={`${card} space-y-3 p-5`}><div className="flex items-center gap-2"><UserRound size={18} className="text-[#ff8b63]"/><h2 className="font-black">Profil</h2></div><input name="name" defaultValue={data.member.name} className={input} required/><input value={data.member.email} className={`${input} opacity-60`} readOnly/><input name="whatsapp" defaultValue={data.member.whatsapp||""} className={input} placeholder="WhatsApp"/><input value={data.member.referral_code} className={`${input} font-mono opacity-60`} readOnly/><button className={primary}>Simpan Profil</button></form><form onSubmit={e=>void save(e,"password")} className={`${card} h-fit space-y-3 p-5`}><h2 className="font-black">Ganti password</h2><input name="currentPassword" type="password" className={input} placeholder="Password saat ini" required/><input name="newPassword" type="password" minLength={8} className={input} placeholder="Password baru minimal 8 karakter" required/><button className={primary}>Ganti Password</button><p className="text-xs leading-5 text-slate-500">Bergabung {new Date(data.member.joined_at).toLocaleDateString("id-ID")} • T&C {data.terms?.terms_version||"-"}</p></form></div></>}

function Help({data}:{data:any}){const faq=[["Kapan poin masuk?",`Setelah transaksi pertama customer baru sukses. Nilai saat ini ${data.referralPoints} poin.`],["Apakah repeat order dapat poin lagi?","Tidak untuk reward referral pertama customer baru."],["Berapa nilai poin?",`1 poin saat ini bernilai Rp ${fmt(data.pointValue)} untuk withdrawal.`],["Mengapa poin di-hold?","Agar poin tidak digunakan dua kali ketika redemption atau withdrawal sedang diproses."],["Minimum withdrawal?",`${data.minimumWithdrawal} poin.`],["Berapa lama attribution?",`${data.referralWindowDays} hari dengan last-click.`],["Apakah self-referral dapat poin?","Tidak."],["Bagaimana leaderboard dihitung?","Dari poin referral reward valid pada periode bulanan berjalan."]];return <><Head eyebrow="Cara Kerja Member" title="Lima langkah yang mudah dipahami" text="Nilai yang bisa berubah dibaca dari setting Member aktual."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{["Bagikan link","Teman checkout","Transaksi sukses","Dapat poin","Tukar reward"].map((x,i)=><div key={x} className={`${card} p-4`}><span className="grid h-8 w-8 place-items-center rounded-full bg-[#ff6b35] text-sm font-black">{i+1}</span><p className="mt-3 font-bold">{x}</p></div>)}</div><div className="grid gap-3 md:grid-cols-2">{faq.map(([q,a])=><details key={q} className={`${card} p-4`}><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 text-sm leading-6 text-slate-400">{a}</p></details>)}</div></>}

function List({title,rows,empty}:{title:string;rows:Array<{id:any;title:string;sub:string;right?:string|null}>;empty:string}){return <section><h2 className="mb-3 font-black">{title}</h2>{rows.length?<div className={`${card} divide-y divide-white/6`}>{rows.map(x=><div key={x.id} className="flex items-center justify-between gap-4 p-4"><div><p className="font-bold">{x.title}</p><p className="mt-1 text-xs text-slate-500">{x.sub}</p></div>{x.right&&<p className="shrink-0 font-black text-emerald-300">{x.right}</p>}</div>)}</div>:<Empty title={empty} text="Data akan muncul otomatis ketika aktivitas tersedia."/>}</section>}
function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className={`${card} grid min-h-40 place-items-center p-6 text-center`}><div><Sparkles size={20} className="mx-auto text-slate-600"/><p className="mt-3 font-black">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p>{action&&<div className="mt-4">{action}</div>}</div></div>}
function Loading(){return <div className="space-y-4"><div className="h-24 animate-pulse rounded-2xl bg-white/[.04]"/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:4},(_,i)=><div key={i} className="h-24 animate-pulse rounded-2xl bg-white/[.04]"/>)}</div><div className="grid min-h-56 place-items-center rounded-2xl border border-white/8 bg-[#111a2a]"><div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 size={17} className="animate-spin"/>Memuat Member Portal...</div></div></div>}
