"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Loader2, Search } from "lucide-react";

export type AdminSection="list"|"rewards"|"redemptions"|"withdrawals"|"leaderboard"|"points"|"settings"|"activity";
const card="rounded-xl border border-white/8 bg-white/[.025]";
const input="w-full rounded-lg border border-white/10 bg-white/[.03] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent-primary)]";
const primary="inline-flex items-center justify-center rounded-lg bg-[var(--accent-primary)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40";
const secondary="inline-flex items-center justify-center rounded-lg border border-white/10 bg-white/[.03] px-4 py-2.5 text-sm font-semibold";
const date=(v:any)=>new Date(v).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"});
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function AdminMemberSectionClient({section}:{section:AdminSection}){
 const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const [q,setQ]=useState("");const [status,setStatus]=useState("all");const [sort,setSort]=useState("joined_desc");
 const endpoint=section==="list"||section==="points"?`/api/admin/members?q=${encodeURIComponent(q)}&status=${status}&sort=${sort}`:`/api/admin/members/${section}`;
 async function load(){setLoading(true);setError("");try{const r=await fetch(endpoint,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Gagal memuat data");setData(j)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[section]);
 async function send(url:string,method:string,body:any){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setNotice(j.error||"Gagal memproses");return false}setNotice("Perubahan berhasil disimpan.");await load();return true}
 if(loading)return <div className={`${card} grid min-h-48 place-items-center`}><Loader2 className="animate-spin"/></div>;
 if(error)return <div className={`${card} p-5 text-rose-300`}>{error}</div>;
 const props={data,load,send,notice,setNotice,q,setQ,status,setStatus,sort,setSort};
 return <>{notice&&<div role="status" className="mb-4 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-300">{notice}</div>}{section==="list"&&<Members {...props}/>} {section==="points"&&<Points {...props}/>} {section==="rewards"&&<Rewards {...props}/>} {section==="redemptions"&&<Requests {...props} kind="redemption"/>} {section==="withdrawals"&&<Requests {...props} kind="withdrawal"/>} {section==="leaderboard"&&<Leaderboard {...props}/>} {section==="settings"&&<Settings {...props}/>} {section==="activity"&&<Activity {...props}/>}</>;
}

function Filters({q,setQ,status,setStatus,sort,setSort,load}:{q:string;setQ:any;status:string;setStatus:any;sort:string;setSort:any;load:any}){return <div className={`${card} flex flex-col gap-2 p-3 md:flex-row`}><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 opacity-50"/><input className={`${input} pl-9`} value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, email, atau referral code"/></div><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Semua status</option><option value="active">Active</option><option value="left">Left</option></select><select className={input} value={sort} onChange={e=>setSort(e.target.value)}><option value="joined_desc">Terbaru</option><option value="joined_asc">Terlama</option><option value="points_desc">Poin tertinggi</option><option value="referrals_desc">Referral tertinggi</option></select><button className={primary} onClick={()=>void load()}>Terapkan</button></div>}

function Members(p:any){const rows=Array.isArray(p.data)?p.data:[];return <div className="space-y-4"><Header title="Member List" text="Daftar operasional Member dengan saldo dan performa referral."/><Filters {...p}/>{!rows.length?<Empty/>:<div className={`${card} overflow-x-auto`}><table className="w-full min-w-[900px] text-left text-sm"><thead className="border-b border-white/8 text-xs text-[var(--text-muted)]"><tr><th className="p-4">Member</th><th>Status</th><th>Joined</th><th>Poin</th><th>Referral</th><th>Aksi</th></tr></thead><tbody>{rows.map((m:any)=><tr key={m.id} className="border-b border-white/6 last:border-0"><td className="p-4"><p className="font-bold">{m.name}</p><p className="text-xs text-[var(--text-muted)]">{m.email} • {m.referral_code}</p></td><td>{pretty(m.status)}</td><td>{date(m.joined_at)}</td><td className="font-bold">{m.points}</td><td>{m.referrals}</td><td><Link className={secondary} href={`/dashboard/members/${m.id}`}>Detail</Link></td></tr>)}</tbody></table></div>}</div>}

function Points(p:any){const rows=Array.isArray(p.data)?p.data:[];const [selected,setSelected]=useState("");const [points,setPoints]=useState("");const [reason,setReason]=useState("");return <div className="space-y-4"><Header title="Point Adjustment" text="Koreksi poin hanya dengan alasan yang tercatat di audit trail."/><Filters {...p}/><form onSubmit={async e=>{e.preventDefault();if(!selected)return;const ok=await p.send("/api/admin/members/points","POST",{memberId:selected,points:Number(points),reason});if(ok){setPoints("");setReason("")}}} className={`${card} grid gap-3 p-4 md:grid-cols-[1fr_160px_2fr_auto]`}><select required className={input} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih Member</option>{rows.map((m:any)=><option key={m.id} value={m.id}>{m.name} — {m.points} poin</option>)}</select><input required className={input} type="number" value={points} onChange={e=>setPoints(e.target.value)} placeholder="+ / - poin"/><input required className={input} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Alasan adjustment"/><button className={primary}>Simpan</button></form></div>}

function Rewards(p:any){const rewards=p.data?.rewards||[];const products=p.data?.products||[];const [type,setType]=useState("manual");return <div className="space-y-4"><Header title="Reward" text="Kelola benefit Member dan mapping produk voucher tanpa memasukkan Product ID mentah."/><div className="grid gap-4 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await p.send("/api/admin/members/rewards","POST",Object.fromEntries(f.entries()))}} className={`${card} space-y-3 p-4`}><input name="name" required className={input} placeholder="Nama reward"/><input name="pointsRequired" type="number" min="1" required className={input} placeholder="Poin dibutuhkan"/><select name="fulfillmentType" className={input} value={type} onChange={e=>setType(e.target.value)}><option value="manual">Manual</option><option value="dorizz_voucher">Voucher Dorizz</option></select>{type==="dorizz_voucher"&&<select name="productId" required className={input}><option value="">Pilih produk tujuan</option>{products.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<textarea name="description" className={`${input} min-h-24`} placeholder="Deskripsi reward"/><button className={primary}>Tambah Reward</button></form><div className="space-y-3">{rewards.length?rewards.map((r:any)=><div key={r.id} className={`${card} p-4`}><div className="flex justify-between gap-3"><div><p className="font-bold">{r.name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{r.points_required} poin • {pretty(r.fulfillment_type)}{r.product_name?` • ${r.product_name}`:""} • {r.redemption_count} penukaran</p></div><span className="text-xs">{r.is_active?"Active":"Inactive"}</span></div><button className={`${secondary} mt-3`} onClick={async()=>{const reason=window.prompt(`Alasan ${r.is_active?"menonaktifkan":"mengaktifkan"} reward`);if(reason)await p.send("/api/admin/members/rewards","PATCH",{id:r.id,isActive:!r.is_active,reason})}}>{r.is_active?"Nonaktifkan":"Aktifkan"}</button></div>):<Empty/>}</div></div></div>}

function Requests(p:any&{kind:"redemption"|"withdrawal"}){const rows=Array.isArray(p.data)?p.data:[];const url=`/api/admin/members/${p.kind==="redemption"?"redemptions":"withdrawals"}`;return <div className="space-y-4"><Header title={p.kind==="redemption"?"Redemption Queue":"Withdrawal Queue"} text="Request pending diproses atomik. Reject wajib mempunyai alasan."/>{!rows.length?<Empty/>:<div className="space-y-3">{rows.map((x:any)=><RequestCard key={x.id} x={x} kind={p.kind} send={p.send} url={url}/>)}</div>}</div>}
function RequestCard({x,kind,send,url}:any){const [reason,setReason]=useState("");return <div className={`${card} p-4`}><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="font-bold">{x.member_name}</p><p className="mt-1 text-sm text-[var(--text-muted)]">{kind==="redemption"?`${x.reward_name} • ${x.points} poin`:`${x.points} poin • Rp ${new Intl.NumberFormat("id-ID").format(Number(x.amount_rupiah||0))} • ${x.method} • ${x.account_name}`}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{date(x.created_at)}</p></div><span className="text-sm font-semibold">{pretty(x.status)}</span></div>{x.status==="pending"&&<div className="mt-4 grid gap-2 md:grid-cols-[1fr_auto_auto]"><input className={input} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Alasan reject / catatan approval"/><button className={primary} onClick={()=>void send(url,"PATCH",{id:x.id,decision:"approve",adminNotes:reason||"Approved"})}>Approve</button><button className={secondary} disabled={!reason.trim()} onClick={()=>void send(url,"PATCH",{id:x.id,decision:"reject",rejectionReason:reason})}>Reject</button></div>}</div>}

function Leaderboard(p:any){const campaigns=p.data?.campaigns||[];const prizes=p.data?.prizes||[];const ranks=Array.from({length:10},(_,i)=>i+1);return <div className="space-y-4"><Header title="Leaderboard" text="Campaign Member mendukung hadiah Top 1–10."/><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const ps=ranks.map(rank=>({rank,prizeName:String(f.get(`p${rank}`)||"")})).filter(x=>x.prizeName);await p.send("/api/admin/members/leaderboard","POST",{name:f.get("name"),monthStart:f.get("monthStart"),monthEnd:f.get("monthEnd"),prizes:ps})}} className={`${card} grid gap-3 p-4 md:grid-cols-3`}><input name="name" required className={input} placeholder="Nama campaign"/><input name="monthStart" type="date" required className={input}/><input name="monthEnd" type="date" required className={input}/>{ranks.map(rank=><input key={rank} name={`p${rank}`} className={input} placeholder={`Hadiah Top ${rank}`}/>)}<button className={`${primary} md:col-span-3`}>Buat Campaign</button></form><div className="space-y-3">{campaigns.map((c:any)=><div key={c.id} className={`${card} p-4`}><p className="font-bold">{c.name}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{String(c.month_start).slice(0,10)} — {String(c.month_end).slice(0,10)} • {c.status}</p><div className="mt-3 flex flex-wrap gap-2">{prizes.filter((x:any)=>x.campaign_id===c.id).map((x:any)=><span key={x.id} className="rounded-md bg-white/5 px-2 py-1 text-xs">#{x.rank} {x.prize_name}</span>)}</div></div>)}</div></div>}

const settingMeta:any={referral_points:["Poin per Referral Berhasil","poin"],point_value_rupiah:["Nilai 1 Poin","Rupiah"],minimum_withdraw_points:["Minimum Withdrawal","poin"],referral_window_days:["Masa Attribution Referral","hari"],terms_version:["Versi Syarat & Ketentuan","versi"]};
function Settings(p:any){const rows=Array.isArray(p.data)?p.data:[];return <div className="space-y-4"><Header title="Settings" text="Konfigurasi Member ditampilkan dengan nama manusiawi dan alasan perubahan wajib dicatat."/><div className="grid gap-3 lg:grid-cols-2">{rows.map((x:any)=><SettingCard key={x.key} row={x} send={p.send}/>)}</div></div>}
function SettingCard({row,send}:any){const [value,setValue]=useState(typeof row.value==="string"?row.value:JSON.stringify(row.value).replace(/^\"|\"$/g,""));const [reason,setReason]=useState("");const meta=settingMeta[row.key]||[pretty(row.key),""];return <form onSubmit={e=>{e.preventDefault();void send("/api/admin/members/settings","PATCH",{key:row.key,value:row.key==="terms_version"?value:Number(value),reason})}} className={`${card} space-y-3 p-4`}><div><p className="font-bold">{meta[0]}</p><p className="text-xs text-[var(--text-muted)]">Unit: {meta[1]}</p></div><input className={input} value={value} onChange={e=>setValue(e.target.value)}/><input required className={input} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Alasan perubahan"/><button className={primary}>Simpan</button></form>}

function Activity(p:any){const rows=Array.isArray(p.data)?p.data:[];return <div className="space-y-4"><Header title="Activity Log" text="Jejak perubahan penting yang dilakukan admin pada sistem Member."/><div className={`${card} divide-y divide-white/6`}>{rows.length?rows.map((x:any)=><div key={x.id} className="p-4"><div className="flex flex-col gap-1 md:flex-row md:justify-between"><p className="font-semibold">{pretty(x.action)}</p><p className="text-xs text-[var(--text-muted)]">{date(x.created_at)}</p></div><p className="mt-1 text-xs text-[var(--text-muted)]">Admin: {x.admin_name||"System"}{x.member_name?` • Member: ${x.member_name}`:""}{x.reason?` • Alasan: ${x.reason}`:""}</p></div>):<Empty/>}</div></div>}

function Header({title,text}:{title:string;text:string}){return <div><h2 className="text-2xl font-black">{title}</h2><p className="mt-1 text-sm text-[var(--text-muted)]">{text}</p></div>}
function Empty(){return <div className={`${card} p-8 text-center text-sm text-[var(--text-muted)]`}>Belum ada data.</div>}
