"use client";

import Link from "next/link";
import { useState } from "react";
import { Loader2, LogIn, ShieldCheck, UserPlus } from "lucide-react";

const input="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-950 outline-none placeholder:text-slate-400 transition focus:border-blue-400 focus:ring-4 focus:ring-blue-500/10";
const primary="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-blue-600 via-blue-500 to-sky-400 px-4 py-3 text-sm font-black text-white shadow-sm transition hover:brightness-105 disabled:opacity-50";

export default function MemberClient(){
 const [mode,setMode]=useState<"join"|"login">("join");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");try{const f=new FormData(e.currentTarget);const body:any=Object.fromEntries(f.entries());if(mode==="join")body.acceptTerms=f.get("acceptTerms")==="on";const r=await fetch(mode==="join"?"/api/member/auth/join":"/api/member/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok){setError(j.error||"Gagal memproses Member");return}window.location.href="/member/dashboard";}catch{setError("Terjadi gangguan. Coba lagi.")}finally{setLoading(false)}}
 const steps=[["01","Bagikan link","Bagikan link referral kamu."],["02","Teman checkout","Teman melakukan pembelian melalui linkmu."],["03","Dapat poin","Poin masuk setelah referral berhasil."]];
 return <main className="min-h-screen overflow-hidden bg-white text-slate-950">
  <div className="pointer-events-none absolute inset-x-0 top-0 h-[560px] bg-[radial-gradient(circle_at_78%_25%,rgba(56,189,248,.16),transparent_30%),radial-gradient(circle_at_60%_15%,rgba(37,99,235,.08),transparent_28%)]"/>
  <div className="relative mx-auto max-w-7xl px-5 py-8 sm:px-7 lg:px-10 lg:py-12">
   <section className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
    <div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Member DorizzStore</p><h1 className="mt-4 max-w-2xl text-[2.35rem] font-black leading-[1.08] tracking-[-.035em] sm:text-5xl lg:text-[3.45rem]">Referral, poin, reward,<br className="hidden sm:block"/> dan withdrawal dalam <span className="bg-gradient-to-r from-sky-400 to-blue-600 bg-clip-text text-transparent">satu portal</span> yang jelas.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-500 sm:text-base">Bagikan link referral, pantau progres, lalu gunakan poin untuk reward atau withdrawal sesuai aturan Member yang berlaku.</p></div>
    <div className="relative hidden min-h-[250px] lg:block"><div className="absolute inset-0 rounded-[3rem] bg-gradient-to-br from-sky-50 via-white to-blue-50"/><svg className="absolute inset-0 h-full w-full" viewBox="0 0 600 260" fill="none" aria-hidden="true"><path d="M45 180C130 70 215 220 300 105C380 0 455 190 560 65" stroke="#93C5FD" strokeWidth="1.5" strokeDasharray="5 7"/><path d="M80 70C180 180 245 20 350 145C420 225 480 95 550 170" stroke="#BFDBFE" strokeWidth="1.5"/><circle cx="45" cy="180" r="5" fill="#2563EB"/><circle cx="300" cy="105" r="7" fill="#38BDF8"/><circle cx="560" cy="65" r="5" fill="#2563EB"/><circle cx="350" cy="145" r="5" fill="#60A5FA"/></svg><div className="absolute left-[43%] top-[31%] grid h-24 w-24 place-items-center rounded-[1.8rem] bg-gradient-to-br from-blue-500 to-blue-700 text-5xl font-black text-white shadow-xl shadow-blue-500/20">D</div>{[["18%","25%"],["73%","17%"],["16%","68%"],["76%","63%"],["58%","70%"]].map(([l,t],i)=><div key={i} className="absolute grid h-12 w-12 place-items-center rounded-full border-4 border-white bg-slate-100 shadow-sm" style={{left:l,top:t}}><div className="h-5 w-5 rounded-full bg-slate-300"/></div>)}</div>
   </section>
   <section className="mt-8 grid gap-5 border-y border-slate-100 py-6 sm:grid-cols-3 sm:gap-0">{steps.map(([n,title,text],i)=><div key={n} className={`relative flex gap-4 sm:px-6 ${i?"sm:border-l sm:border-slate-100":""}`}><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl border border-blue-100 bg-blue-50 text-sm font-black text-blue-600">{n}</div><div><p className="font-black text-slate-900">{title}</p><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div>)}</section>
   <section className="mx-auto mt-8 max-w-4xl rounded-2xl border border-blue-100 bg-white p-4 shadow-[0_18px_60px_rgba(37,99,235,.08)] sm:p-6">
    <div className="mb-6 grid grid-cols-2 border-b border-slate-200"><button onClick={()=>{setMode("join");setError("")}} className={`relative px-4 py-3 text-sm font-black transition ${mode==="join"?"text-blue-600":"text-slate-400 hover:text-slate-700"}`}>Daftar{mode==="join"&&<span className="absolute inset-x-0 -bottom-px h-0.5 bg-gradient-to-r from-blue-600 to-sky-400"/>}</button><button onClick={()=>{setMode("login");setError("")}} className={`relative px-4 py-3 text-sm font-black transition ${mode==="login"?"text-blue-600":"text-slate-400 hover:text-slate-700"}`}>Masuk{mode==="login"&&<span className="absolute inset-x-0 -bottom-px h-0.5 bg-gradient-to-r from-blue-600 to-sky-400"/>}</button></div>
    <div className="mx-auto max-w-2xl"><h2 className="text-xl font-black tracking-tight text-slate-950">{mode==="join"?"Buat akun Member":"Masuk ke Member Portal"}</h2><p className="mt-1 text-sm text-slate-500">{mode==="join"?"Referral code dibuat otomatis setelah pendaftaran berhasil.":"Gunakan email dan password Member kamu."}</p><form onSubmit={submit} className="mt-5 space-y-3">{mode==="join"&&<input name="name" required placeholder="Nama lengkap" className={input}/>}<input name="email" type="email" required placeholder="Email" className={input}/>{mode==="join"&&<input name="whatsapp" placeholder="Nomor WhatsApp" className={input}/>}<input name="password" type="password" minLength={8} required placeholder="Password minimal 8 karakter" className={input}/>{mode==="join"&&<label className="flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-3 text-sm text-slate-600"><input name="acceptTerms" type="checkbox" required className="mt-1 accent-blue-600"/><span>Saya menyetujui <Link href="/member/terms" className="font-bold text-blue-600 hover:underline">Syarat & Ketentuan Member</Link>.</span></label>}{error&&<div className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2.5 text-sm text-rose-700">{error}</div>}<button disabled={loading} className={primary}>{loading?<Loader2 size={17} className="animate-spin"/>:mode==="join"?<UserPlus size={17}/>:<LogIn size={17}/>} {loading?"Memproses...":mode==="join"?"Daftar":"Masuk"}</button></form><div className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-400"><ShieldCheck size={14}/>{mode==="join"?"Customer referral tetap checkout normal tanpa login Member.":"Belum punya akun? Pilih Daftar di atas."}</div></div>
   </section>
  </div>
 </main>
}
